---
name: CDOS Business Entities

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 3 * * *'

jobs:
  business_entities_etl:
    name: ETL for CDOS Business Entities
    runs-on: ubuntu-latest
    env:
      CDOS_SFTP_USERNAME: ${{ secrets.CDOS_SFTP_USERNAME }}
      CDOS_SFTP_PASSWORD: ${{ secrets.CDOS_SFTP_PASSWORD }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup pip
        if: ${{ env.ACT }}
        run: |
          curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python get-pip.py
      - name: setup dependencies
        run: npm i
      - name: extract
        run: npm run business_entities:extract
      - name: transform
        run: npm run business_entities:transform
      - name: load
        env:
          MY_SOCRATA_USERNAME: ${{ secrets.MY_SOCRATA_USERNAME }}
          MY_SOCRATA_PASSWORD: ${{ secrets.MY_SOCRATA_PASSWORD }}
          DATASET_ID: 4ykn-tg5h
          UPLOAD_FILE: business_entities.csv
          CONFIG_NAME: business_entities_11-22-2021_f71d
        run: |
          pip install socrata-py~=1.0.0
          python3 socrata-updater.py
