---
name: CDOS Business Entities

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  business_entities_etl:
    name: ETL for CDOS Business Entities
    runs-on: ubuntu-latest
    env:
      CDOS_SFTP_USERNAME: ${{ secrets.CDOS_SFTP_USERNAME }}
      CDOS_SFTP_PASSWORD: ${{ secrets.CDOS_SFTP_PASSWORD }}
      DATASYNC_CONFIG: ${{ secrets.DATASYNC_CONFIG }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download datasync
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: 'https://github.com/socrata/datasync/releases/download/1.9.6/DataSync-1.9.6.jar'
          file-name: 'DataSync.jar'
          location: '../'
      - name: 'java setup'
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: setup dependencies
        run: |
          npm i
          echo $DATASYNC_CONFIG > ../config.json
          java -jar ../DataSync.jar -t LoadPreferences -c ../config.json
      - name: extract
        run: npm run business_entities:extract
      - name: transform
        run: npm run business_entities:transform
      - name: load
        run: npm run business_entities:load
